CREATE PROCEDURE `add_user`(IN n int)
BEGIN  
    DECLARE i INT DEFAULT 1;
    WHILE (i <= n ) DO
        INSERT into user_tab (id, name, created_at, updated_at ) VALUES 
        (i*50, concat('u', i*50), current_timestamp, current_timestamp),
        (i*50 + 1, concat('u', i*50 + 1), current_timestamp, current_timestamp),
        (i*50 + 2, concat('u', i*50 + 2), current_timestamp, current_timestamp),
        (i*50 + 3, concat('u', i*50 + 3), current_timestamp, current_timestamp),
        (i*50 + 4, concat('u', i*50 + 4), current_timestamp, current_timestamp),
        (i*50 + 5, concat('u', i*50 + 5), current_timestamp, current_timestamp),
        (i*50 + 6, concat('u', i*50 + 6), current_timestamp, current_timestamp),
        (i*50 + 7, concat('u', i*50 + 7), current_timestamp, current_timestamp),
        (i*50 + 8, concat('u', i*50 + 8), current_timestamp, current_timestamp),
        (i*50 + 9, concat('u', i*50 + 9), current_timestamp, current_timestamp),
        (i*50 + 10, concat('u', i*50 + 10), current_timestamp, current_timestamp),
        (i*50 + 11, concat('u', i*50 + 11), current_timestamp, current_timestamp),
        (i*50 + 12, concat('u', i*50 + 12), current_timestamp, current_timestamp),
        (i*50 + 13, concat('u', i*50 + 13), current_timestamp, current_timestamp),
        (i*50 + 14, concat('u', i*50 + 14), current_timestamp, current_timestamp),
        (i*50 + 15, concat('u', i*50 + 15), current_timestamp, current_timestamp),
        (i*50 + 16, concat('u', i*50 + 16), current_timestamp, current_timestamp),
        (i*50 + 17, concat('u', i*50 + 17), current_timestamp, current_timestamp),
        (i*50 + 18, concat('u', i*50 + 18), current_timestamp, current_timestamp),
        (i*50 + 19, concat('u', i*50 + 19), current_timestamp, current_timestamp),
        (i*50 + 20, concat('u', i*50 + 20), current_timestamp, current_timestamp),
        (i*50 + 21, concat('u', i*50 + 21), current_timestamp, current_timestamp),
        (i*50 + 22, concat('u', i*50 + 22), current_timestamp, current_timestamp),
        (i*50 + 23, concat('u', i*50 + 23), current_timestamp, current_timestamp),
        (i*50 + 24, concat('u', i*50 + 24), current_timestamp, current_timestamp),
        (i*50 + 25, concat('u', i*50 + 25), current_timestamp, current_timestamp),
        (i*50 + 26, concat('u', i*50 + 26), current_timestamp, current_timestamp),
        (i*50 + 27, concat('u', i*50 + 27), current_timestamp, current_timestamp),
        (i*50 + 28, concat('u', i*50 + 28), current_timestamp, current_timestamp),
        (i*50 + 29, concat('u', i*50 + 29), current_timestamp, current_timestamp),
        (i*50 + 30, concat('u', i*50 + 30), current_timestamp, current_timestamp),
        (i*50 + 31, concat('u', i*50 + 31), current_timestamp, current_timestamp),
        (i*50 + 32, concat('u', i*50 + 32), current_timestamp, current_timestamp),
        (i*50 + 33, concat('u', i*50 + 33), current_timestamp, current_timestamp),
        (i*50 + 34, concat('u', i*50 + 34), current_timestamp, current_timestamp),
        (i*50 + 35, concat('u', i*50 + 35), current_timestamp, current_timestamp),
        (i*50 + 36, concat('u', i*50 + 36), current_timestamp, current_timestamp),
        (i*50 + 37, concat('u', i*50 + 37), current_timestamp, current_timestamp),
        (i*50 + 38, concat('u', i*50 + 38), current_timestamp, current_timestamp),
        (i*50 + 39, concat('u', i*50 + 39), current_timestamp, current_timestamp),
        (i*50 + 40, concat('u', i*50 + 40), current_timestamp, current_timestamp),
        (i*50 + 41, concat('u', i*50 + 41), current_timestamp, current_timestamp),
        (i*50 + 42, concat('u', i*50 + 42), current_timestamp, current_timestamp),
        (i*50 + 43, concat('u', i*50 + 43), current_timestamp, current_timestamp),
        (i*50 + 44, concat('u', i*50 + 44), current_timestamp, current_timestamp),
        (i*50 + 45, concat('u', i*50 + 45), current_timestamp, current_timestamp),
        (i*50 + 46, concat('u', i*50 + 46), current_timestamp, current_timestamp),
        (i*50 + 47, concat('u', i*50 + 47), current_timestamp, current_timestamp),
        (i*50 + 48, concat('u', i*50 + 48), current_timestamp, current_timestamp),
        (i*50 + 49, concat('u', i*50 + 49), current_timestamp, current_timestamp)
        ;
        SET i=i+1;
    END WHILE;
END;
